name: codigo_de_estrada_mz
description: Website do aplicativo código de estrada MZ. A melhor forma de estudar o código de estrada no celular.
version: 2.0.3+15

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  rxdart: ^0.27.7
  bloc_pattern: ^3.0.1
  shared_preferences: ^2.0.17
  sqflite: ^2.2.4+1
  url_launcher: ^6.1.9
  fluttertoast: ^8.2.1
  flare_flutter: ^3.0.2
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.8
  firebase_analytics: ^10.1.3
  firebase_messaging: ^14.2.5
  google_sign_in: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_inapp_purchase: ^5.3.1
  package_info: ^2.0.2
  carousel_slider: ^4.2.1
  path_provider: ^2.0.12
  connectivity: ^3.0.6
  provider: ^6.0.5
  firebase_core: ^2.7.0
  flutter_facebook_auth: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/launcher/cde.png'
  image_path_android: 'assets/launcher/cde.png'
  adaptive_icon_background: 'assets/launcher/background.png'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/launcher/
    - assets/screenshots/
    - assets/info/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 500
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
