name: codigo_de_estrada_mz
description: Website do aplicativo código de estrada MZ. A melhor forma de estudar o código de estrada no celular.
version: 2.0.3+15

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.24.0
  bloc_pattern: ^3.0.0
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.5
  url_launcher: ^5.1.4
  fluttertoast: ^3.1.3
  flutter_swiper: ^1.1.6
  flare_flutter: ^1.6.2
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  cloud_firestore: ^0.12.9+4
  firebase_messaging: ^5.1.6
  firebase_auth: ^0.14.0+5
  firebase_analytics: ^5.0.2
  flutter_auth_buttons: ^0.5.0
  flutter_facebook_login: ^3.0.0
  firebase_admob: ^0.9.3+2
  admob_flutter: ^0.3.1
  google_sign_in: ^4.0.7
  flutter_launcher_icons: ^0.7.3
  flutter_inapp_purchase: ^2.0.3
  countdown: ^0.1.0
  package_info: ^0.4.0+3
  carousel_slider: ^0.0.7
  path_provider: ^1.6.5
  connectivity: ^0.4.3+1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/launcher/cde.png'
  image_path_android: 'assets/launcher/cde.png'
  adaptive_icon_background: 'assets/launcher/background.png'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/launcher/
    - assets/screenshots/
    - assets/info/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 500
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
