// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxSXRyGlFCprHPeeQo4WwAfxP0idi9KpU',
    appId: '1:910817423270:android:6ccfe7e4cd8448b2bfe967',
    messagingSenderId: '910817423270',
    projectId: 'codigo-de-estrada-mz',
    databaseURL: 'https://codigo-de-estrada-mz.firebaseio.com',
    storageBucket: 'codigo-de-estrada-mz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBO72qZDAGAUZMSksA43vNJhDDGx5FfU',
    appId: '1:910817423270:ios:f5512fcbe87845a2bfe967',
    messagingSenderId: '910817423270',
    projectId: 'codigo-de-estrada-mz',
    databaseURL: 'https://codigo-de-estrada-mz.firebaseio.com',
    storageBucket: 'codigo-de-estrada-mz.appspot.com',
    androidClientId: '910817423270-qbsi6df5rj5e3pdkdmdvm4taiu11n1qe.apps.googleusercontent.com',
    iosClientId: '910817423270-3p3av2mcrrnei4jncom2g180k8oju6gf.apps.googleusercontent.com',
    iosBundleId: 'mz.co.chillstudio.codigoDeEstradaMz',
  );
}
